#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -e

if [ "$1" = purge ]; then
    rm -rf /etc/eus /var/lib/eus /var/log/eus /etc/systemd/system/eus-refresh.timer.d
fi
if [ "$1" = remove ] || [ "$1" = purge ]; then
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload >/dev/null 2>&1 || true
    fi
fi

exit 0
