#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop eus-sources.path eus-refresh.timer >/dev/null 2>&1 || true
    fi
    systemctl disable eus-sources.path eus-refresh.timer >/dev/null 2>&1 || true
fi

exit 0
