#!/usr/bin/env bash
# Regenerate tools/install-eduka-update-system-cubic.sh from this checkout.
# The result is one self-contained script (the source tree is embedded as a
# compressed archive) for ISO work in Cubic when the repository is not copied
# into the chroot. SPDX-License-Identifier: GPL-3.0-or-later
set -Eeuo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUTPUT="${1:-$PROJECT_DIR/tools/install-eduka-update-system-cubic.sh}"
VERSION="$(tr -d '[:space:]' <"$PROJECT_DIR/VERSION")"

{
    cat <<HEADER
#!/bin/bash
# Eduka-Update-System (EUS) ${VERSION} self-contained installer for Edukasaun OS / Debian.
# Generated by tools/build-cubic-installer.sh - do not edit by hand.
#
# Inside the Cubic terminal (chroot), as root:
#   bash install-eduka-update-system-cubic.sh            # installs missing dependencies too
#   bash install-eduka-update-system-cubic.sh --no-deps  # files only
# Test without touching the system:
#   EUS_INSTALL_ROOT=/tmp/eus-root bash install-eduka-update-system-cubic.sh
set -Eeuo pipefail

EUS_VERSION='${VERSION}'
HEADER
    cat <<'BODY'
WORK_DIR="$(mktemp -d -t eus-cubic.XXXXXXXX)"
trap 'rm -rf -- "$WORK_DIR"' EXIT

if [[ -z "${EUS_INSTALL_ROOT:-}" && "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "ERROR: Run this installer as root (sudo bash $0)." >&2
    exit 1
fi

echo "Installing Eduka-Update-System ${EUS_VERSION}..."
sed -n '/^__EUS_ARCHIVE_BELOW__$/,$p' "$0" | tail -n +2 | base64 -d | tar -xz -C "$WORK_DIR"
if [[ -n "${EUS_INSTALL_ROOT:-}" ]]; then
    bash "$WORK_DIR/eduka-update-system/install.sh" --destdir "$EUS_INSTALL_ROOT" "$@"
else
    bash "$WORK_DIR/eduka-update-system/install.sh" "$@"
fi
exit 0
__EUS_ARCHIVE_BELOW__
BODY
    tar -C "$PROJECT_DIR" --transform 's,^\.,eduka-update-system,' \
        --exclude='__pycache__' --owner=0 --group=0 --sort=name \
        -czf - ./install.sh ./uninstall.sh ./VERSION ./LICENSE ./requirements-system.txt \
        ./src ./data ./assets ./config | base64 -w 76
} >"$OUTPUT.tmp"
chmod 0755 "$OUTPUT.tmp"
mv -f -- "$OUTPUT.tmp" "$OUTPUT"
printf '%s\n' "$OUTPUT"
